### First Stage ###
FROM node:14.16.0-alpine3.10 AS builder

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

ARG BASE_URL
ENV ANGULAR_APP_BASE_URL=${BASE_URL}

RUN npm run build --prod

### Second Stage ###
FROM caddy:2.3.0-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile
RUN rm -rf /srv/*
COPY --from=builder /app/dist/frontend/ /srv

EXPOSE 80

EXPOSE 443
